version: '3.9'

services:
  pgdatabase:
    image: postgres
    container_name: pgdatabase
    ports:
      - 5432:5432
    volumes:
      - db:/var/lib/postgresql/data
    environment:
      - POSTGRES_PASSWORD=root
      - POSTGRES_USER=root
      - POSTGRES_DB=ny_taxi
    networks: 
      - pg-network
  pgadmin: 
    image: dpage/pgadmin4
    container_name: pgadmin
    environment: 
      - PGADMIN_DEFAULT_EMAIL=admin@admin.com
      - PGADMIN_DEFAULT_PASSWORD=root
    ports: 
      - 8080:80
    networks: 
      - pg-network 

volumes:
  db: 
    external: true

networks: 
  pg-network: 
    external: true 